package site.gutschi.quarkustestextension.runtime.log

import jakarta.enterprise.context.ApplicationScoped

@ApplicationScoped
class LoggingService {
    val invocations: MutableList<Invocation> = mutableListOf()

    @Suppress("unused") // Function is called by generated bytecode
    fun startInvocation(className: String, methodName: String, args: Array<Any>): RunningInvocation {
        return RunningInvocation(className, methodName, args)
    }

    fun getInvocations(clazz: Class<*>?, method: String?): List<Invocation> {
        return invocations
            .filter { clazz == null || it.className == clazz.name }
            .filter { it.methodName == method || method == null }
    }

    inner class RunningInvocation(val className: String, val methodName: String, val args: Array<out Any?>) {
        @Suppress("unused") // Function is called by generated bytecode
        fun finishWithResult(result: Any) {
            invocations.add(Invocation(className, methodName, args, result, null))
        }

        @Suppress("unused") // Function is called by generated bytecode
        fun finishWithoutResult() {
            invocations.add(Invocation(className, methodName, args, null, null))
        }

        @Suppress("unused") // Function is called by generated bytecode
        fun finishWithException(throwable: Throwable) {
            invocations.add(Invocation(className, methodName, args, null, throwable))
        }
    }
}

@Suppress("ArrayInDataClass") // Data class with array property is intentional, this is a new invocation
@SuppressWarnings("kotlin:S6218") // Data class with array property is intentional, this is a new invocation
data class Invocation(val className: String, val methodName: String, val args: Array<out Any?>, val result: Any?, val throwable: Throwable?)